[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography", "no-std", "algorithms"]
description = "Verifiable Secret Sharing Schemes for splitting, combining and verifying secret shares"
documentation = "https://docs.rs/vsss-rs"
edition = "2018"
homepage = "https://github.com/mikelodder/vsss-rs"
keywords = ["crypto", "sharing", "secret", "verifiable"]
license = "Apache-2.0"
name = "vsss-rs"
readme = "README.md"
repository = "https://github.com/mikelodder7/vsss-rs"
version = "1.0.0"

[features]
default = ["curve25519"]
curve25519 = ["curve25519-dalek", "subtle"]

[dependencies]
curve25519-dalek = { version = "4.0.0-pre.0", optional = true }
ff = "0.10"
group = "0.10"
rand_chacha = { version = "0.3", default-features = false }
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["serde_derive"] }
subtle = { version = "2.4", optional = true }
zeroize = { version = "1.3", features = ["zeroize_derive"] }

[dev-dependencies]
bls12_381_plus = "0.5"
curve25519-dalek = "4.0.0-pre.0"
ed25519-dalek = "1.0"
k256 = { version = "0.9", features = ["arithmetic", "bits"] }
p256 = { version = "0.9", features = ["arithmetic", "bits"] }
rand = "0.8"
rand_7 = { version = "0.7", package = "rand" }
rand_xorshift = "0.3"
sha2 = "0.9"
x25519-dalek = "1.1"
