[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
description = "Verifiable Secret Sharing Schemes for splitting, combining and verifying secret shares"
documentation = "https://docs.rs/vsss-rs"
edition = "2018"
homepage = "https://github.com/mikelodder/vsss-rs"
keywords = ["cryptography", "sharing", "secret", "verifiable"]
license = "Apache-2.0"
name = "vsss-rs"
readme = "README.md"
repository = "https://github.com/mikelodder7/vsss-rs"
version = "0.1.0"

[features]
alloc = []
std = []

[dependencies]
ff = "0.10"
group = "0.10"
rand_core = "0.6"
serde = { version = "1.0", features = ["serde_derive"] }
zeroize = { version = "1.3", features = ["zeroize_derive"] }
